import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "../components/Layout";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/providers/AuthProviders";
import EditModal from "@/components/modals/EditModal";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
          <Toaster />
          <RegisterModal />
          <LoginModal />
          <EditModal />
          <Layout>{children}</Layout>
      </AuthProvider>
      </body>
    </html>
  );
}
